import marshal
import sys
from argparse import ArgumentParser
from pathlib import Path
from types import CodeType

from spasm._pyc import PycUnmarshalError
from spasm._pyc import PycWriteError
from spasm._pyc import write_pyc

# _version.py is generated by setuptools-scm at build time, so it is absent
# from a fresh checkout; the ignore keeps mypy quiet there. It reads as unused
# once the package has been built at least once.
from spasm._version import __version__  # type: ignore[import]
from spasm.asm import Assembly
from spasm.asm import OpArg
from spasm.bytecode import UNSET


class SpasmError(Exception):
    pass


class SpasmUnmarshalError(SpasmError):
    pass


def dump_code_to_file(code: CodeType, file: Path) -> None:
    try:
        write_pyc(code, file)
    except PycUnmarshalError as e:
        msg = "Cannot unmarshal code object"
        raise SpasmUnmarshalError(msg) from e
    except PycWriteError as e:
        msg = "Cannot assemble source to pyc file"
        raise SpasmError(msg) from e


def assemble(sourcefile: Path) -> CodeType:
    asm = Assembly(name="<module>", filename=str(sourcefile.resolve()), lineno=1)
    asm.parse(sourcefile.read_text())
    return asm.compile()


def find_unmarshallable_objects(asm: Assembly) -> None:
    for instr in asm._instrs:
        if type(instr) is not OpArg:
            continue
        if instr.arg is not None and instr.arg is not UNSET:
            try:
                marshal.dumps(instr.arg)
            except Exception:
                print(  # noqa: T201
                    f"  in {asm._filename}, line {instr.lineno}: object "
                    f"of type {type(instr.arg)} cannot be unmarshalled"
                )

    for code in asm._codes.values():
        find_unmarshallable_objects(code)


def spasm(sourcefile: Path) -> None:
    try:
        asm = Assembly(name="<module>", filename=str(sourcefile.resolve()), lineno=1)

        asm.parse(sourcefile.read_text())

        code = asm.compile()

        dump_code_to_file(code, sourcefile.with_suffix(".pyc"))

    except Exception as e:
        print("Spasm error:", str(e))  # noqa: T201
        if isinstance(e, SpasmUnmarshalError):
            find_unmarshallable_objects(asm)
        raise


def main() -> None:
    argp = ArgumentParser()

    argp.add_argument("file", type=Path)
    argp.add_argument("-V", "--version", action="version", version=__version__)

    args = argp.parse_args()

    try:
        spasm(args.file)
    except Exception:
        sys.exit(1)


if __name__ == "__main__":
    main()
